import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  guideSidebar: [
    { type: 'doc', id: 'intro', label: '介绍' },
    { type: 'doc', id: 'quickstart', label: '快速开始' },
    { type: 'doc', id: 'architecture', label: '架构设计' },
    { type: 'doc', id: 'server', label: 'HTTP Server' },
  ],
  apiSidebar: [
    {
      type: 'category',
      label: 'API 参考',
      items: [{ type: 'autogenerated', dirName: 'api' }],
    },
  ],
};

export default sidebars;
